---
apiVersion: v1
kind: List
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      creationTimestamp: null
      name: "eirini-helloworld-extension"
    rules:
    - apiGroups:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
  - kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: "eirini-helloworld-extension"
      namespace: "default"
    roleRef:
      kind: ClusterRole
      name: "eirini-helloworld-extension"
      apiGroup: rbac.authorization.k8s.io
    subjects:
    - kind: ServiceAccount
      name: "eirini-helloworld-extension"
      namespace: "default"