kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eirini-helloworld-extension
subjects:
- kind: ServiceAccount
  name: eirini-helloworld-extension
roleRef:
  kind: Role
  name: eirini-helloworld-extension
  apiGroup: rbac.authorization.k8s.io